### ISSUE TITLE
Spelling typo in cmdlet Get-ExectionPolicy (missing u)

### ISSUE THREAD

**Issue by NL12143** [microsoft/Bio-Compliancy#5]
My 50 cents to make it possible that everyone (on the planet) can use this:  

Error in "4. Voer het volgende commando uit: Get-ExectionPolicy"
Almost invisible but it should be Get-Exec**u**tionPolicy (ie missing a "u"). Small error for us, blocking for normal users.

Suggest to add some details how to do an "Open een elevated 'Windows PowerShell v5.1' window .."
Windows > Start > Powershell or ISE, Run as Adminstrator > Check for "Administrator: " in the title bar. 
Check it is starting in "PS> C:Windows\system32". Change this to folder. For example do Set-Location "C:\BIO"  

Great project ! Hope it gets popular with most organisations. Will do my best to advertise it in the community events. 
Found it as i am playing with the idea to use MS365DSC to check for the well known "gratis" security enhancements.

**Comment by ykuijs** [comment]
Thanks @NL12143, great spot. I will correct it!

**Comment by ykuijs** [comment]
For the other suggestion:
Playing devils advocate here, but if you don't know how to start an elevated PowerShell window should you run these scripts at all?

I would say we should expect a certain level of expertise. Since these scripts are meant for M365 admins, I hope that those know how to start an elevated PS session.

What is your opinion?
